extends Node

var cutscene = [
	[ "type_text", "", 0.1 ],
	[ "wait", 1 ],
	[ "type_text", "_______________________", 0.1 ],
	[ "show_text", "A long time ago" ],
	[ "wait_for_input", 0 ],
	[ "show_text", "a developer went to" ],
	[ "wait_for_input", 0 ],
	[ "show_text", "update core" ],
	[ "wait_for_input", 0 ],
	[ "play_audio", "res://Cutscene/sample.wav" ],
	[ "type_text", "drush pm-update drupal", 0.09 ],
	[ "wait_for_input", 0 ],
	[ "show_text", "but not that long ago" ],
	[ "wait_for_input", 0 ],
	[ "play_audio", "res://Cutscene/sample.wav" ],
	[ "delete_text", "drush pm-update drupal", 0.04 ],
	[ "show_text", "it was in Drupal 8" ],
	[ "wait_for_input", 0 ],
	[ "play_audio", "res://Cutscene/sample.wav" ],
	[ "type_text", "cp --force --recursive", 0.09 ],
	[ "wait_for_input", 0 ],
	[ "show_text", "as recommended" ],
	[ "wait_for_input", 0 ],
	[ "show_text", "on drupal.org" ],
	[ "wait_for_input", 0 ],
	[ "play_audio", "res://Cutscene/sample.wav" ],
	[ "delete_text", "cp --force --rec", 0.04 ],
	[ "play_audio", "res://Cutscene/sample.wav" ],
	[ "type_text", "composer update", 0.15 ],
	[ "wait", 1 ],
	[ "show_text", "there we go" ],
	[ "wait_for_input", 2 ],
	[ "play_audio", "res://Cutscene/sample.wav" ],
	[ "type_text", "drupal/core", 0.1 ],
	[ "wait", 1 ],
	[ "play_audio", "res://Cutscene/sample.wav" ],
	[ "type_text", "--with-dependencies", 0.1 ],
	[ "wait", 1 ],
	[ "show_text", "But somehow" ],
	[ "wait_for_input", 2 ],
	[ "show_text", "everything got updated" ],
	[ "wait_for_input", 2 ],
	[ "show_text", "except" ],
	[ "wait_for_input", 2 ],
	[ "show_text", "for core." ],
	[ "wait_for_input", 2 ],
	[ "show_text", "This is where" ],
	[ "wait_for_input", 2 ],
	[ "show_text", "our story begins." ],
	[ "wait_for_input", 2 ],
	#[ "show_text", "Like all modern web projects" ],
	#[ "wait", 3 ],
	#[ "show_text", "with a dependency issue." ],
	#[ "wait", 3 ],
	[ "show_text", "" ],
	[ "wait", 2 ],
	[ "load_scene", "story1" ],
]

func _ready():
	var cutscene_processor = get_node("CutsceneProcessor")
	cutscene_processor.cutscene_array = cutscene
	print(cutscene_processor.cutscene_array)