extends Node

var cutscene = [
	[ "type_text", "", 0.1 ],
	[ "wait", 3 ],
	[ "play_audio", "res://Cutscene/sample.wav" ],
	[ "type_text", "drupal quest story", 0.1 ],
	[ "wait", 2 ],
	[ "show_text", "A long time ago" ],
	[ "wait_for_input", 2 ],
	[ "show_text", "a developer went to" ],
	[ "wait", 2 ],
	[ "show_text", "update core." ],
	[ "wait", 2 ],
	[ "play_audio", "res://Cutscene/sample.wav" ],
	[ "type_text", "drush pm-update drupal", 0.1 ],
	[ "wait", 0.5 ],
	[ "show_text", "not that long ago" ],
	[ "wait", 2 ],
	[ "play_audio", "res://Cutscene/sample.wav" ],
	[ "delete_text", "drush pm-update drupal", 0.1 ],
	[ "wait", 1 ],
	[ "play_audio", "res://Cutscene/sample.wav" ],
	[ "type_text", "composer update", 0.15 ],
	[ "wait", 1 ],
	[ "play_audio", "res://Cutscene/sample.wav" ],
	[ "type_text", "drupal/core", 0.1 ],
	[ "wait", 1 ],
	[ "play_audio", "res://Cutscene/sample.wav" ],
	[ "type_text", "--with-dependencies", 0.1 ],
	[ "wait", 1 ],
	[ "show_text", "But somehow" ],
	[ "wait", 2 ],
	[ "show_text", "everything got updated" ],
	[ "wait", 2 ],
	[ "show_text", "EXCEPT" ],
	[ "wait", 2 ],
	[ "show_text", "for core." ],
	[ "wait", 2 ],
	[ "show_text", "This is where" ],
	[ "wait", 2 ],
	[ "show_text", "our story begins." ],
	[ "wait", 2 ],
	[ "show_text", "Like all modern web projects" ],
	[ "wait", 3 ],
	[ "show_text", "with a dependency issue." ],
	[ "wait", 3 ],
	[ "show_text", "" ],
	[ "wait", 2 ],
	[ "load_scene", "story1" ],
]

func _ready():
	var cutscene_processor = get_node("CutsceneProcessor")
	cutscene_processor.cutscene_array = cutscene
	print(cutscene_processor.cutscene_array)